services:
  backend:
    build:
      context: ./backend_asp
    ports:
      - "5089:5089"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=StockMarket;User=root;Password=root;
    depends_on:
      - db

  frontend:
    build:
      context: ./stockmarket
    ports:
      - "4200:80"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: StockMarket
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
